# Generated by Django 4.1.2 on 2023-04-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(verbose_name=5)),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=200)),
                ('rollno', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('mobile', models.IntegerField()),
                ('guardian_mobile', models.IntegerField()),
            ],
        ),
    ]
