# Generated by Django 4.1.2 on 2023-04-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_dob_alter_student_studentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentId',
        ),
    ]
